############ DO NOT CHANGE THESE #################
SUPPORTED:=./uart:./pwm:./bootrom:./clint:./common_bsv:./fabrics/axi4:./fabrics/axi4lite:./fabrics/tilelink_lite:./bram:./gpio:./sdram
TOP_MODULE:=mkdummy

############# User changes to be done below #################
DIR:=
TOP_DIR:= 
TOP_FILE:=

